name: Docker Build and Push

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set repository name to lowercase
      id: repo-name
      run: echo "repo_name=$(echo ${{ github.repository }} | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push mp3-api image
      uses: docker/build-push-action@v4
      with:
        context: ./mp3-api
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: |
          ghcr.io/${{ env.repo_name }}/mp3-api:latest
          ghcr.io/${{ env.repo_name }}/mp3-api:${{ github.sha }}

    - name: Build and push adapter image
      uses: docker/build-push-action@v4
      with:
        context: ./adapter
        push: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        tags: |
          ghcr.io/${{ env.repo_name }}/adapter:latest
          ghcr.io/${{ env.repo_name }}/adapter:${{ github.sha }}
